### ISSUE TITLE
If the number of feature arguments is 0, then it is not mandatory

### ISSUE THREAD

**Issue by waltdisgrace** [stratis-storage/devicemapper-rs#484] opened 2019-07-16 14:43 UTC
We must modify our code, because we are currently treating the number of feature arguments as mandatory.

Evidence for the number of feature arguments not being mandatory:

1. The [DM source code](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/md) implements feature parsing such that supplying no feature arguments is allowed.
2. The [DM documentation](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/device-mapper) does not indicate that the number of feature arguments is mandatory.
3. Testing out various dmsetup commands shows that even when no number of feature arguments is supplied, a device can be created. See example below:

[gchin@to-be-determined devicemapper-rs]$ lsblk
NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda      8:0    0 119.2G  0 disk 
├─sda1   8:1    0     1G  0 part /boot
├─sda2   8:2    0  11.9G  0 part [SWAP]
├─sda3   8:3    0    50G  0 part /
├─sda4   8:4    0     1K  0 part 
└─sda5   8:5    0  56.3G  0 part /home
sdb      8:16   0 111.8G  0 disk 
├─sdb1   8:17   0     4G  0 part 
├─sdb2   8:18   0     5G  0 part 
└─sdb3   8:19   0     5G  0 part 
[gchin@to-be-determined devicemapper-rs]$ sudo dmsetup create flakey1 --table '0 8388608 flakey 8:17 0 10 10'
[gchin@to-be-determined devicemapper-rs]$ lsblk
NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda           8:0    0 119.2G  0 disk 
├─sda1        8:1    0     1G  0 part /boot
├─sda2        8:2    0  11.9G  0 part [SWAP]
├─sda3        8:3    0    50G  0 part /
├─sda4        8:4    0     1K  0 part 
└─sda5        8:5    0  56.3G  0 part /home
sdb           8:16   0 111.8G  0 disk 
├─sdb1        8:17   0     4G  0 part 
│ └─flakey1 253:0    0     4G  0 dm   
├─sdb2        8:18   0     5G  0 part 
└─sdb3        8:19   0     5G  0 part

**Comment by mulkieran** [comment] 2019-07-16 14:52
Can you also show the result of "dmsetup table" command on the flakey device that you created?

**Comment by waltdisgrace** [comment] 2019-07-16 15:45
[gchin@to-be-determined devicemapper-rs]$ sudo dmsetup table
flakey1: 0 8388608 flakey 8:17 0 10 10 0

**Comment by mulkieran** [comment] 2019-07-23 14:32
Note that this varies w/ the target. It seems to be mandatory for cache device, according to the docs, but it not mandatory for thinpool. That will have to be fixed up as well, although the bug is somewhat different in the thinpool implementation.

The worst instance of the problem is in flakey, because the use of the index operator is an unguarded assertion.

**Comment by mulkieran** [comment] 2019-08-02 12:22
Closed by #495 and #489. Turns out that the number of feature args is mandatory for cache dev, and thindev and linear dev do not have feature args. So this is done.

**Closed by mulkieran** 2019-08-02 12:22 UTC
